server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: Yq1mzeCkLBIh5vdxYmGKW62MyRbsvfNGnZyEPGPVWnARJIFUay0VVnqTMRT91Zp2y4njvK4TyScIU5hy5sQ
