server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

jwt:
  secret: Yq1mzeCkLBIh5vdxYmGKW62MyRbsvfNGnZyEPGPVWnARJIFUay0VVnqTMRT91Zp2y4njvK4TyScIU5hy5sQ
